# Generated by Django 5.0.4 on 2026-06-11 12:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('advocate', 'Advocate'), ('critic', 'Critic'), ('judge', 'Judge')], max_length=20)),
                ('round_number', models.IntegerField(default=1)),
                ('content', models.TextField(blank=True, default='')),
                ('advocate_score', models.FloatField(blank=True, null=True)),
                ('critic_score', models.FloatField(blank=True, null=True)),
                ('advocate_logic_score', models.FloatField(blank=True, null=True)),
                ('critic_logic_score', models.FloatField(blank=True, null=True)),
                ('verdict', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('rebuttal', 'Rebuttal Round'), ('judging', 'Judging'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('snippet', models.TextField(blank=True, default='')),
                ('index', models.IntegerField(default=1)),
                ('agent_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='debates.agentoutput')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='agentoutput',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_outputs', to='debates.debate'),
        ),
    ]
