# Generated by Django 5.0.4 on 2026-06-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Round 1 – Advocate'), ('round_2', 'Round 2 – Critic'), ('round_3', 'Round 3 – Advocate'), ('round_4', 'Round 4 – Critic'), ('judging', 'Judging'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
