# Generated by Django 5.0.4 on 2026-06-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0002_alter_debate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentoutput',
            name='turn',
            field=models.CharField(default='advocate', max_length=10),
        ),
        migrations.AddField(
            model_name='debate',
            name='num_rounds',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='debate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('judging', 'Judging'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
